name: UAT Release Pipeline

on:
    workflow_dispatch:

jobs:
    deploy-azure:
        name: Deploy to Azure Web App
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: Log in to Docker Hub
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

            - name: Pull Docker image
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              run: |
                  docker pull $DOCKER_USERNAME/hrs-api:uat-latest

            - name: Azure Login
              uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  global-json-file: global.json

            - name: Run EF Core migrations
              env:
                  ConnectionStrings__DefaultConnection: ${{ secrets.TF_MYSQL_CONNECTION_STRING }}
              run: |
                  dotnet tool install --global dotnet-ef --version 8.0.7
                  dotnet ef database update --project HRS.Migrations --startup-project HRS.API

            - name: Deploy container
              uses: azure/webapps-deploy@122b7ec46017e53a3f71e3a027d67550a1641f5e # v2.2.17
              with:
                  app-name: web-hrs-api-uat
                  images: ${{ secrets.DOCKER_USERNAME }}/hrs-api:uat-latest
